name: Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout del repositorio
        uses: actions/checkout@v4

      - name: 🔨 Construir la imagen Docker
        run: docker build -t piedra-papel-tijera .

      - name: 🚀 Install Vercel CLI
        run: npm install -g vercel

      - name: 🔑 Autenticarse en Vercel
        run: vercel login
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: 📦 Deploy to Vercel using Docker
        run: vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
